CREATE TABLE fornecedores (
  id INT AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  sobrenome VARCHAR(50) NOT NULL,
  CNPJ VARCHAR(20) NOT NULL,
  INSC VARCHAR(20) NOT NULL,
  endereco VARCHAR(100) NOT NULL,
  bairro VARCHAR(50) NOT NULL,
  uf VARCHAR(2) NOT NULL,
  cep VARCHAR(10) NOT NULL,
  estado VARCHAR(50) NOT NULL,
  pais VARCHAR(50) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  email VARCHAR